site:
  title: Antora Docs
  start_page: root::hello.adoc
content:
  sources:
  - url: ./site/docs
    branches: HEAD
    start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

antora:
  extensions:
  - '@antora/collector-extension'
